const fs=require('fs'),vm=require('vm');
let code=fs.readFileSync('data.js','utf8');
code += "\n;this.ENDINGS=ENDINGS;this.IDENTITIES=IDENTITIES;";
const ctx={Math,console};vm.createContext(ctx);vm.runInContext(code,ctx);
const E=ctx.ENDINGS,I=ctx.IDENTITIES;
const keys=Object.keys(E);
let byK={};keys.forEach(k=>{const t=E[k].k;byK[t]=(byK[t]||0)+1;});
const ident=Object.keys(I).length;
const mid=keys.filter(k=>E[k].k!=='ascend').length;
console.log('=== ENDINGS 总计 ===', keys.length);
console.log('按 k 字段分布:', JSON.stringify(byK));
console.log('good(善终):', byK.good||0, ' bad(凶终):', byK.bad||0, ' grey:', byK.grey||0, ' ascend:', byK.ascend||0, ' cut:', byK.cut||0, ' poor:', byK.poor||0);
console.log('---');
console.log('列传(身份 IDENTITIES) 条目数 =', ident);
console.log('殁录(结局, 跳过飞升 ascend) 条目数 =', mid, '  (全结局', keys.length, '- 飞升', byK.ascend||0, ')');
console.log('---');
console.log('青史界面显示: 列传', ident, '格 + 殁录', mid, '格 = 你看到的 12 / 62');
